# Generated by Django 5.0.7 on 2024-07-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('slug', models.SlugField(default='')),
                ('photographer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.photographer')),
            ],
        ),
    ]
