# Generated by Django 5.0.7 on 2024-07-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
