# Generated by Django 5.0.7 on 2024-08-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_photo_file_remove_photo_url_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_small',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
