# Generated by Django 5.0.7 on 2024-08-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_small',
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
