# Generated by Django 5.0.7 on 2024-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_alter_photo_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_small',
            field=models.FileField(editable=False, null=True, upload_to='images/small'),
        ),
    ]
