# Generated by Django 5.0.7 on 2025-04-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samjd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='project_images')),
                ('alt_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, to='samjd.projectimage'),
        ),
    ]
