# Generated by Django 5.0.7 on 2025-04-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samjd', '0004_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
