# Generated by Django 5.0.7 on 2025-04-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samjd', '0005_project_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subheading',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
