# Generated by Django 5.0.7 on 2025-04-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samjd', '0007_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='cert',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
