# Generated by Django 5.0.7 on 2025-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samjd', '0008_cert_image_cert_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('active', 'active'), ('inactive', 'inactive')], null=True),
        ),
    ]
