name: Deploy master
on:
  push:
    branches:
    - master

env:
  DJANGO_WEBSITE_ENVIRONMENT: "BUILD"
  S3_WRITE_USER_ACCESS_KEY: ${{ secrets.S3_WRITE_USER_ACCESS_KEY }}
  S3_WRITE_SECRET_ACCESS_KEY: ${{ secrets.S3_WRITE_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
    
    - name: Install Django
      run: pip install django django-storages boto3 pillow

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set version label
      run: |
        short_sha=$(git rev-parse --short "${{ github.sha }}")
        echo 'version=${{ github.ref_name }}:'$short_sha >> "$GITHUB_ENV"
      
    - name: Collect static files
      run: python manage.py collectstatic --no-input

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*' -x '**/static/*'

