name: Deploy master
on:
  push:
    branches:
    - master

env:
  DJANGO_WEBSITE_ENVIRONMENT: "BUILD"
  AWS_ACCESS_KEY: ${{ secrets.UPLOAD_WEBSITE_CODE_PACKAGES_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.UPLOAD_WEBSITE_CODE_PACKAGES_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    
    - name: Install Django
      run: pip install django django-storages boto3 pillow

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set version label
      run: |
        short_sha=$(git rev-parse --short "${{ github.sha }}")
        echo 'version=${{ github.ref_name }}:'$short_sha >> "$GITHUB_ENV"
      
    - name: Collect static files
      env: 
        AWS_ACCESS_KEY: ${{ secrets.UPLOAD_WEBSITE_CODE_PACKAGES_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.UPLOAD_WEBSITE_CODE_PACKAGES_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2
      run: python manage.py collectstatic --no-input

    - name: Generate deployment package
      run: zip -Ar '${{ env.version }}-latest' . -x '*.git*' -x '**/static/*'

    - name: Upload source package to bucket
      run: |
        export AWS_ACCESS_KEY_ID='${{ env.AWS_ACCESS_KEY }}'
        export AWS_SECRET_ACCESS_KEY='${{ env.AWS_SECRET_ACCESS_KEY }}'
        export AWS_DEFAULT_REGION=ap-southeast-2
        export OLD_PACKAGE=`aws s3api list-objects --bucket website-source-packages-github-actions-upload | jq -r '.Contents[].Key | select( endswith("latest") )'`
        aws s3 cp '${{ env.version }}-latest' 's3://website-source-packages-github-actions-upload/${{ env.version }}-latest'
        aws s3 rm 's3://website-source-packages-github-actions-upload/$OLD_PACKAGE'
        export WEB_INSTANCE=`aws ec2 describe-spot-instance-requests --no-paginate | jq '.SpotInstanceRequests.[0].InstanceId'`
        aws ec2 modify-spot-fleet-request \
          --spot-fleet-request-id sfr-af22f6b6-e582-428a-841f-ae483c4614a0 \
          --target-capacity 2
        sleep 180s
        aws ec2 modify-spot-fleet-request \
          --spot-fleet-request-id sfr-af22f6b6-e582-428a-841f-ae483c4614a0 \
          --target-capacity 1 \
          --excess-capacity-termination-policy noTermination
        aws ec2 terminate-instance --instance-ids $WEB_INSTANCE
